# Generated by Django 5.1.6 on 2025-02-26 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the contest', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Name of the contest', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of the contest (inclusive)')),
                ('end_date', models.DateField(help_text='End date of the contest (inclusive)')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the prize', max_length=50)),
                ('name', models.CharField(help_text='Name of the prize', max_length=255)),
                ('perday', models.PositiveIntegerField(help_text='Maximum number of times this prize can be won per day')),
                ('contest', models.ForeignKey(help_text='The contest this prize belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contests.contest')),
            ],
            options={
                'unique_together': {('code', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='WinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, help_text='Optional identifier for the user who won the prize', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the prize was won')),
                ('prize', models.ForeignKey(help_text='The prize that was won', on_delete=django.db.models.deletion.CASCADE, related_name='win_records', to='contests.prize')),
            ],
        ),
    ]
